# 工作流名称
name: Go CI

# 触发事件
on:
    push:
        branches: [main] # 当推送到 main 分支时触发
    pull_request:
        branches: [main] # 当提交 PR 到 main 分支时触发

# 任务定义
jobs:
    build-and-test: # 任务名称
        runs-on: ubuntu-latest # 使用最新的 Ubuntu runner

        steps:
            # 步骤 1：检出代码
            - name: Checkout code
              uses: actions/checkout@v4

            # 步骤 2：设置 Go 环境
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22' # 指定 Go 版本

            # 步骤 3：安装依赖
            - name: Install dependencies
              run: go mod tidy

            # 步骤 4：构建项目
            - name: Build
              run: go build -v ./...

            # 步骤 5：运行测试
            - name: Test
              run: go test -v ./...

            # 步骤 6（可选）：上传构建产物
            - name: Upload artifact
              if: success() # 仅在成功时执行
              uses: actions/upload-artifact@v4
              with:
                  name: go-binary # 产物名称
                  path: ./go-github-actions-demo # 构建的可执行文件路径
